project:
  type: website

website:
  title: "Paul Jacobson"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - projects.qmd
      - about.qmd

    right:
      - icon: github
        href: https://github.com/pajacobson
      - icon: linkedin
        href: https://www.linkedin.com/in/paul-jacobson-15b069247/


format:
  html:
    minimal: true
    theme: simplex
    css: /css/main.css
    toc: true



