project:
  type: website

website:
  title: "Paul Jacobson"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - projects.qmd
      - text: About
        href: about.qmd

format:
  html:
    minimal: true
    theme: litera
    css: /css/main.css
    toc: true

execute:
  freeze: auto



