<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-10-03">

<title>Paul Jacobson - Cyclistic Customer Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../css/main.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Paul Jacobson</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html">Projects</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Cyclistic Customer Analysis</h1>
            <p class="subtitle lead">Google Data Analytics Certificate Capstone</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 3, 2022</p>
      </div>
    </div>
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="abstract-title">Summary</div>
      An analysis of historical Divvy Bikes ride data to identify differences in user cohort behaviour.
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#defining-the-business-task" id="toc-defining-the-business-task" class="nav-link" data-scroll-target="#defining-the-business-task">Defining the business task</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data sources</a>
  <ul class="collapse">
  <li><a href="#divvy-bikes-system-data-and-pricing" id="toc-divvy-bikes-system-data-and-pricing" class="nav-link" data-scroll-target="#divvy-bikes-system-data-and-pricing">Divvy Bikes system data and pricing</a></li>
  <li><a href="#noaa-climate-data" id="toc-noaa-climate-data" class="nav-link" data-scroll-target="#noaa-climate-data">NOAA Climate Data</a></li>
  <li><a href="#divvy-bikes-historical-station-status" id="toc-divvy-bikes-historical-station-status" class="nav-link" data-scroll-target="#divvy-bikes-historical-station-status">Divvy Bikes historical station status</a></li>
  </ul></li>
  <li><a href="#data-cleaning-and-preparation" id="toc-data-cleaning-and-preparation" class="nav-link" data-scroll-target="#data-cleaning-and-preparation">Data cleaning and preparation</a>
  <ul class="collapse">
  <li><a href="#initial-import" id="toc-initial-import" class="nav-link" data-scroll-target="#initial-import">Initial import</a></li>
  <li><a href="#data-inspection" id="toc-data-inspection" class="nav-link" data-scroll-target="#data-inspection">Data inspection</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="background" class="level1">
<h1>Background</h1>
<p>In 2016 Cyclistic launched a bike-sharing sharing offering which has grown to a fleet of 6000 geotracked bicycles and network of more than 1000 stations across Chicago.</p>
<p>Analysis by Cyclistic’s finance team has determined that riders who purchase annual memberships are more profitable than casual riders.</p>
<p>Head of marketing, Lily Moreno, has set a goal of designing marketing strategies aimed at converting casual riders to members. The intial step is to better understand how casual users and members differ. This information will provide a basis for members of the marketing analytics team to investigate why casual riders might purchase a membership, and how digital media could influence marketing strategy.</p>
<p>The executive team, which is detail oriented, will decide whether the proposed marketing strategies are approved.</p>
</section>
<section id="defining-the-business-task" class="level1">
<h1>Defining the business task</h1>
<p>The scope of this analysis is limited to the first step, and investigates the question:</p>
<blockquote class="blockquote">
<p>How do annual members and casual riders use Cyclistic bikes differently?</p>
</blockquote>
<p>Unpacking this question highlights a number of areas that may provide useful insights.</p>
<section id="what-defines-a-member-and-a-casual-rider" class="level4">
<h4 data-anchor-id="what-defines-a-member-and-a-casual-rider">What defines a member and a casual rider?</h4>
<p>The Divvy Bikes pricing information indicates members pay an upfront annual fee to access pricing that includes “no-charge” ride time and lower per minute charges. Casual riders access ride sharing on an ad-hoc basis, paying a per-ride charge, and higher per minute charge which begins when the bike is undocked. Daily pass riders pay a day access fee to access unlimited 3 hour rides for the duration of the pass.</p>
</section>
<section id="what-influence-do-the-plans-have-on-the-user-behaviour" class="level4">
<h4 data-anchor-id="what-influence-do-the-plans-have-on-the-user-behaviour">What influence do the plans have on the user behaviour?</h4>
<p>Can we distinguish plan types by the average duration of rides? What percentage of riders exceed the included 45 minutes ride time of membership plans? Is this same for members and casuals?</p>
<p>This may help identify if time inclusions are a factor for casual riders considering membership.</p>
</section>
<section id="when-do-different-user-cohorts-ride" class="level4">
<h4 data-anchor-id="when-do-different-user-cohorts-ride">When do different user cohorts ride?</h4>
<p>Which days, and times are popular for the different cohorts? And are there identifiable differences or commonality in behaviours?</p>
</section>
<section id="does-weather-influence-rider-behaviour" class="level4">
<h4 data-anchor-id="does-weather-influence-rider-behaviour">Does weather influence rider behaviour?</h4>
<p>Are the types and number of rides related to day-to-day variations in weather or broader seasonal patterns? Are casual users “all season” or “fair weather” riders? Casual riders who ride around the year could be a group that would find membership attractive.</p>
</section>
<section id="where-do-different-user-cohorts-ride" class="level4">
<h4 data-anchor-id="where-do-different-user-cohorts-ride">Where do different user cohorts ride?</h4>
<p>Riders commuting to work are likely to use docking stations in business districts during the week. Recreational riders may prefer parks and areas along the shoreline or cafe precincts. Docking stations with high levels of usage on different days of the week should provide insight into where user hotspots are located.</p>
</section>
</section>
<section id="data-sources" class="level1">
<h1>Data sources</h1>
<section id="divvy-bikes-system-data-and-pricing" class="level3">
<h3 data-anchor-id="divvy-bikes-system-data-and-pricing">Divvy Bikes system data and pricing</h3>
<p>The base data for individual rides was extracted from Divvy Bike data files covering the period 1 September 2021 to 31 August 2022. Additional data description and a download link is provided on the Divvy Bikes <a href="https://ride.divvybikes.com/system-data">system data</a> page.</p>
<p>The <a href="https://ride.divvybikes.com/data-license-agreement">license</a> allows inclusion of data within analyses and studies published for non-commercial. This clause covers the intended use.</p>
<p>Details of current <a href="https://ride.divvybikes.com/pricing">pricing</a> for Divvy Bikes offerings was accessed on 25 September 2022.</p>
</section>
<section id="noaa-climate-data" class="level3">
<h3 data-anchor-id="noaa-climate-data">NOAA Climate Data</h3>
<p>Weather data covering September 2021 to August 2022 ordered from <a href="https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USW00094846/detail">NOOA National Centers for Environmental Information</a></p>
<p>O’Hare International Airport weather station was selected as representative of the Chicago region.</p>
</section>
<section id="divvy-bikes-historical-station-status" class="level3">
<h3 data-anchor-id="divvy-bikes-historical-station-status">Divvy Bikes historical station status</h3>
<p>Historical station status identifies which stations actively used between September 2021 and August 2022. This information is used to assist identifying Divvy operational rides in the data set.</p>
<p><a href="https://data.cityofchicago.org/Transportation/Divvy-Bicycle-Stations/bbyy-e7gq">City of Chicago open data listing of Divvy Stations</a></p>
</section>
</section>
<section id="data-cleaning-and-preparation" class="level1">
<h1>Data cleaning and preparation</h1>
<section id="initial-import" class="level3">
<h3 data-anchor-id="initial-import">Initial import</h3>
<div class="cell">

</div>
<p>The Divvy trip data files have a consistent naming format <code>YYYYMM-divvy-tripdata.zip</code>. This allows file names to be generated for months in the range September 2021 to August 2022.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1" data-caption="Building file list"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>divvy_files <span class="ot">&lt;-</span> <span class="fu">seq</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my</span>(params<span class="sc">$</span>start_date),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my</span>(params<span class="sc">$</span>end_date),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"months"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">enframe</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> <span class="st">"timestamp"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glue_data</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"{year(timestamp)}"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"{stringi::stri_sprintf('%02d', month(timestamp))}"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"-divvy-tripdata.zip"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
</div>
<p>To preserve a local copy of the original data, zip files are downloaded to the <code>data/raw</code> folder. The folder is checked each time the script is run, and files which are already present are removed from the download list.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>divvy_downloaded <span class="ot">&lt;-</span> <span class="fu">glue</span>(<span class="st">"data/raw/{divvy_files}"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>to_dl <span class="ot">&lt;-</span> divvy_files[<span class="sc">!</span><span class="fu">file.exists</span>(divvy_downloaded)]</span></code></pre></div>
</details>
</div>
<p>Any files which are not present in the <code>data/raw</code>folder are downloaded.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that the preceding section will not execute</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># correctly in a Quarto document.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A script for the full import process can be found in the</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Github repository.</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(to_dl) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">download.file</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">glue</span>(<span class="st">"https://divvy-tripdata.s3.amazonaws.com/{to_dl}"</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">glue</span>(<span class="st">"data/raw/{to_dl}"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</details>
</div>
<p>The first 1000 rows are read from September 2021 zip file. This allows <code>read_csv</code> to determine the type of data in each column. The “guessed” column type specification can then inspected using the <code>spec</code> function.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bike_inspect <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  divvy_downloaded[<span class="dv">1</span>],</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="fu">archive_read</span>(.) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">n_max =</span> <span class="dv">1000</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(bike_inspect)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  ride_id = col_character(),
  rideable_type = col_character(),
  started_at = col_datetime(format = ""),
  ended_at = col_datetime(format = ""),
  start_station_name = col_character(),
  start_station_id = col_character(),
  end_station_name = col_character(),
  end_station_id = col_character(),
  start_lat = col_double(),
  start_lng = col_double(),
  end_lat = col_double(),
  end_lng = col_double(),
  member_casual = col_character()
)</code></pre>
</div>
</div>
<p>The types defined in the column specification appear to be reasonable choices based on naming of the columns.</p>
<p>To verify column naming is consistent across all files, the header row from each file is read. The resulting data frame is processed using <code>distinct()</code> to eliminate duplicated rows. If all headers are identical the resulting data frame will have a single row.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bike_headers <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  divvy_downloaded,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="fu">archive_read</span>(.) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">n_max =</span> <span class="dv">1</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">col_names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(bike_headers)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1 × 13] (S3: tbl_df/tbl/data.frame)
 $ X1 : chr "ride_id"
 $ X2 : chr "rideable_type"
 $ X3 : chr "started_at"
 $ X4 : chr "ended_at"
 $ X5 : chr "start_station_name"
 $ X6 : chr "start_station_id"
 $ X7 : chr "end_station_name"
 $ X8 : chr "end_station_id"
 $ X9 : chr "start_lat"
 $ X10: chr "start_lng"
 $ X11: chr "end_lat"
 $ X12: chr "end_lng"
 $ X13: chr "member_casual"</code></pre>
</div>
</div>
<p>After verifying the detected formats, and checking column naming is consistent across all files, the full dataset can be imported. Passing the full column specification to <code>read_csv()</code> ensure that data which does not match the expected type is flagged as a problem. Issues that arise while importing data can be examined using the <code>problems()</code> function.</p>
<div class="cell" data-hash="cyclistic_cache/html/code-import-from-zip_0ef5ebe9f08921c121f122a1baa89f46">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  divvy_downloaded,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> <span class="fu">archive_read</span>(.) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">col_types =</span> <span class="fu">cols</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ride_id =</span> <span class="fu">col_character</span>(),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">rideable_type =</span> <span class="fu">col_factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>          <span class="st">"classic_bike"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>          <span class="st">"docked_bike"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>          <span class="st">"electric_bike"</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        )),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">started_at =</span> <span class="fu">col_datetime</span>(),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">ended_at =</span> <span class="fu">col_datetime</span>(),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_station_name =</span> <span class="fu">col_character</span>(),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_station_id =</span> <span class="fu">col_character</span>(),</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_station_name =</span> <span class="fu">col_character</span>(),</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_station_id =</span> <span class="fu">col_character</span>(),</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_lat =</span> <span class="fu">col_double</span>(),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_lng =</span> <span class="fu">col_double</span>(),</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_lat =</span> <span class="fu">col_double</span>(),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_lng =</span> <span class="fu">col_double</span>(),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">member_casual =</span> <span class="fu">col_factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>          <span class="st">"member"</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>          <span class="st">"casual"</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>        ))</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">tz =</span> <span class="st">"America/Chicago"</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
</div>
</section>
<section id="data-inspection" class="level3">
<h3 data-anchor-id="data-inspection">Data inspection</h3>
<p>With the data loaded from file, the data structure can checked with <code>glimpse()</code>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,883,043
Columns: 13
$ ride_id            &lt;chr&gt; "9DC7B962304CBFD8", "F930E2C6872D6B32", "6EF7213790…
$ rideable_type      &lt;fct&gt; electric_bike, electric_bike, electric_bike, electr…
$ started_at         &lt;dttm&gt; 2021-09-28 16:07:10, 2021-09-28 14:24:51, 2021-09-…
$ ended_at           &lt;dttm&gt; 2021-09-28 16:09:54, 2021-09-28 14:40:05, 2021-09-…
$ start_station_name &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Clark St &amp;…
$ start_station_id   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "TA13070001…
$ end_station_name   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ end_station_id     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ start_lat          &lt;dbl&gt; 41.89000, 41.94000, 41.81000, 41.80000, 41.88000, 4…
$ start_lng          &lt;dbl&gt; -87.68000, -87.64000, -87.72000, -87.72000, -87.740…
$ end_lat            &lt;dbl&gt; 41.89, 41.98, 41.80, 41.81, 41.88, 41.88, 41.74, 41…
$ end_lng            &lt;dbl&gt; -87.67, -87.67, -87.72, -87.72, -87.71, -87.74, -87…
$ member_casual      &lt;fct&gt; casual, casual, casual, casual, casual, casual, cas…</code></pre>
</div>
</div>
<p>The output indicates that the data set has 5883043 rows, and 13 columns. The <code>start_station_name</code>, <code>start_stattion_id</code>, <code>end_station_name</code> and <code>end_station_id</code> columns appear to have a number of missing values - identified by <code>NA</code>.</p>
<p>The extent of the missing information can be assessed by counting the number of <code>NA</code> values in each column.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">everything</span>(),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.x))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Column"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"Missing Count"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-missing-values">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1: Missing Values</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: right;">Missing Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ride_id</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">rideable_type</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">started_at</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ended_at</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">start_station_name</td>
<td style="text-align: right;">884365</td>
</tr>
<tr class="even">
<td style="text-align: left;">start_station_id</td>
<td style="text-align: right;">884363</td>
</tr>
<tr class="odd">
<td style="text-align: left;">end_station_name</td>
<td style="text-align: right;">946303</td>
</tr>
<tr class="even">
<td style="text-align: left;">end_station_id</td>
<td style="text-align: right;">946303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">start_lat</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">start_lng</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">end_lat</td>
<td style="text-align: right;">5727</td>
</tr>
<tr class="even">
<td style="text-align: left;">end_lng</td>
<td style="text-align: right;">5727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">member_casual</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-missing-values">Table&nbsp;1</a> indicates a significant number of records are missing end and start station name and id. End station location information is also missing small number of records. All other columns have complete data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_start =</span> <span class="fu">is.na</span>(start_station_name),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_end =</span> <span class="fu">is.na</span>(end_station_name)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Start Only"</span> <span class="ot">=</span> <span class="fu">sum</span>(missing_start <span class="sc">&amp;</span> <span class="sc">!</span>missing_end),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"End Only"</span> <span class="ot">=</span> <span class="fu">sum</span>(missing_end <span class="sc">&amp;</span> <span class="sc">!</span>missing_start),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Both =</span> <span class="fu">sum</span>(missing_start <span class="sc">&amp;</span> missing_end),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Rides effected"</span> <span class="ot">=</span> <span class="fu">sum</span>(missing_start <span class="sc">|</span> missing_end)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-missing-by-station">
<table class="table table-sm table-striped">
<caption>Table&nbsp;2: Missing Values by station type</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Start Only</th>
<th style="text-align: right;">End Only</th>
<th style="text-align: right;">Both</th>
<th style="text-align: right;">Rides effected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">376594</td>
<td style="text-align: right;">438532</td>
<td style="text-align: right;">507771</td>
<td style="text-align: right;">1322897</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-missing-by-station">Table&nbsp;2</a> indicates that 22.49% of all rides are missing data for at least one docking station. This represents significant number of data points, and should be checked to determine whether this is an error or there have been systematic changes made.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lat =</span> <span class="fu">range</span>(start_lat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lng =</span> <span class="fu">range</span>(start_lng, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_lat =</span> <span class="fu">range</span>(end_lat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_lng =</span> <span class="fu">range</span>(end_lng, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-coord-range">
<table class="table table-sm table-striped">
<caption>Table&nbsp;3: Latitude and Longitude ranges</caption>
<thead>
<tr class="header">
<th style="text-align: right;">start_lat</th>
<th style="text-align: right;">start_lng</th>
<th style="text-align: right;">end_lat</th>
<th style="text-align: right;">end_lng</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">41.64000</td>
<td style="text-align: right;">-87.84000</td>
<td style="text-align: right;">41.39</td>
<td style="text-align: right;">-88.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">45.63503</td>
<td style="text-align: right;">-73.79648</td>
<td style="text-align: right;">42.37</td>
<td style="text-align: right;">-87.50</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>The maximum start longitude and latitude values listed in <a href="#tbl-coord-range">Table&nbsp;3</a> are significantly different to the remaining values. This suggests some rides may have originated outside the Chicago metropolitan area serviced by Cyclistic.</p>
<p>It appears that some latitude and longitude values may have been rounded to two significant digits. Comparing the value to itself rounded to 2 decimal places identifies potentially truncated values. Clamping the coordinates in this way means actual locations can be anywhere within 1 square kilometre area centred on the given grid location.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">Missing =</span> <span class="fu">is.na</span>(start_station_id)) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Latitude =</span> <span class="fu">sum</span>(start_lat <span class="sc">==</span> <span class="fu">round</span>(start_lat, <span class="dv">2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Longitude =</span> <span class="fu">sum</span>(start_lng <span class="sc">==</span> <span class="fu">round</span>(start_lng, <span class="dv">2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-clipped-start">
<table class="table table-sm table-striped">
<caption>Table&nbsp;4: Clipped coordinates and missing start station name</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Missing</th>
<th style="text-align: right;">Latitude</th>
<th style="text-align: right;">Longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">78535</td>
<td style="text-align: right;">78530</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">884363</td>
<td style="text-align: right;">884363</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Comparing <a href="#tbl-missing-values">Table&nbsp;1</a> with <a href="#tbl-clipped-start">Table&nbsp;4</a> indicates the count of start stations with missing names is the same as those which have rounded coordinates.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">Missing =</span> <span class="fu">is.na</span>(end_station_id)) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Latitude =</span> <span class="fu">sum</span>(end_lat <span class="sc">==</span> <span class="fu">round</span>(end_lat, <span class="dv">2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Longitude =</span> <span class="fu">sum</span>(end_lng <span class="sc">==</span> <span class="fu">round</span>(end_lng, <span class="dv">2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-clipped-end">
<table class="table table-sm table-striped">
<caption>Table&nbsp;5: Clipped coordinates and missing end station name</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Missing</th>
<th style="text-align: right;">Latitude</th>
<th style="text-align: right;">Longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">71004</td>
<td style="text-align: right;">71002</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">940576</td>
<td style="text-align: right;">940576</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Comparing <a href="#tbl-missing-values">Table&nbsp;1</a> with <a href="#tbl-clipped-end">Table&nbsp;5</a> indicates the combined count of end stations with missing latitude and longitude and those with rounded coordinates matches the count of missing end station names.</p>
<p>This suggests that there is a systemic reason for the missing data, rather than error. It seems likely the location data has been anonymised to protect riders privacy. This needs to be verified with Cyclistics data collection team.</p>
<p>The ride duration and other information appear plausible and the lack of location data does not impact analysis of this data. Records with missing location information will be retained but filtered for any analysis which depends on accurate location.</p>
<p>While the majority of rounded coordinates occur where station names are missing approximately 8% are for stations which are named. These need to be checked during cleaning.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_range =</span> <span class="fu">range</span>(started_at),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_range =</span> <span class="fu">range</span>(ended_at)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-date-ranges">
<table class="table table-sm table-striped">
<caption>Table&nbsp;6: Ride start and end date ranges</caption>
<thead>
<tr class="header">
<th style="text-align: left;">start_range</th>
<th style="text-align: left;">end_range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2021-09-01 00:00:06</td>
<td style="text-align: left;">2021-09-01 00:00:41</td>
</tr>
<tr class="even">
<td style="text-align: left;">2022-08-31 23:59:39</td>
<td style="text-align: left;">2022-09-06 21:49:04</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-date-ranges">Table&nbsp;6</a> indicates the dataset includes rides which finished after August 2022.</p>
<div class="cell">

</div>
<p>In total 6431 rides are active at midnight on 31 August 2022. Of these, 48 rides are still active at 9.00am on 1 September 2022. As these overnight rides are excluded from the start of the data set, I’ve opted to retain rides which completed prior to 9.00am to ensure this group of riders is not under represented.</p>
</section>
<section id="data-cleaning" class="level3">
<h3 data-anchor-id="data-cleaning">Data Cleaning</h3>
<section id="missing-end-station-coordinates" class="level4">
<h4 data-anchor-id="missing-end-station-coordinates">Missing end station coordinates</h4>
<p>The end stations with missing name and coordinates are addressed first.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>no_end_coords <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(end_lat), <span class="fu">is.na</span>(end_lng))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>no_end_coords <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>ride_id,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"start_"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-no-end-coords">
<table class="table table-sm table-striped">
<caption>Table&nbsp;7: Missing end station coordinates</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">rideable_type</th>
<th style="text-align: left;">started_at</th>
<th style="text-align: left;">ended_at</th>
<th style="text-align: left;">end_station_name</th>
<th style="text-align: left;">end_station_id</th>
<th style="text-align: right;">end_lat</th>
<th style="text-align: right;">end_lng</th>
<th style="text-align: left;">member_casual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-21 15:09:23</td>
<td style="text-align: left;">2021-09-21 16:40:03</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-26 08:32:12</td>
<td style="text-align: left;">2021-09-26 11:50:59</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="odd">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-04 13:52:02</td>
<td style="text-align: left;">2021-09-04 17:21:15</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-22 10:01:36</td>
<td style="text-align: left;">2021-09-23 11:01:27</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="odd">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-10 22:48:46</td>
<td style="text-align: left;">2021-09-11 23:48:39</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-15 01:53:24</td>
<td style="text-align: left;">2021-09-16 02:53:18</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">casual</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>The preview of these rides contains several rides which extend for more than a day. Cyclistic treat bikes unlocked for more than 24 hours as stolen. These rides are likely to be bikes that have been reported stolen and not physically docked at the ride termination time.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>no_end_coords <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">member_casual =</span> <span class="fu">recode</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    member_casual,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"member"</span> <span class="ot">=</span> <span class="st">"Member"</span>, <span class="st">"casual"</span> <span class="ot">=</span> <span class="st">"Casual"</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">triptime =</span> <span class="fu">as.numeric</span>(started_at <span class="sc">%--%</span> ended_at, <span class="at">units =</span> <span class="st">"days"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(triptime, <span class="at">fill =</span> member_casual)) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(member_casual)) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Rides with missing end coordinates by ride type"</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Trip Duration in Days"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Rides"</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
</details>
<div class="cell-output-display">
<p><img src="cyclistic_files/figure-html/unnamed-chunk-16-1.svg" width="672"></p>
</div>
</div>
<p>The plot shows that around 5000 of the 5727 rides terminated after more than 24 hours. Notably casual rides are the biggest contributor.</p>
</section>
<section id="cyclistic-operational-rides" class="level4">
<h4 data-anchor-id="cyclistic-operational-rides">Cyclistic operational rides</h4>
<p>A list of stations that were <em>In-Service</em> between September 2021 and August 2022 was extracted from a dataset maintained by City of Chicago. The dataset for the period of interest contains over 35 million rows recording the status of each docking station at hour intervals.</p>
<p>Due to the size of the dataset the processed listing of stations is used in this analysis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>active_stations <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/processed/stations_in_use.csv"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>active_stations <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>id)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-stations-in-use">
<table class="table table-sm table-striped">
<caption>Table&nbsp;8: Stations recorded as in-service</caption>
<thead>
<tr class="header">
<th style="text-align: left;">timestamp</th>
<th style="text-align: left;">station_name</th>
<th style="text-align: right;">latitude</th>
<th style="text-align: right;">longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2021-10-14 21:25:35</td>
<td style="text-align: left;">Central Park Ave &amp; Ohio St</td>
<td style="text-align: right;">41.89187</td>
<td style="text-align: right;">-87.71639</td>
</tr>
<tr class="even">
<td style="text-align: left;">2022-07-07 14:15:27</td>
<td style="text-align: left;">Public Rack - Franklin Park</td>
<td style="text-align: right;">41.86149</td>
<td style="text-align: right;">-87.73340</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021-08-31 05:05:35</td>
<td style="text-align: left;">N Damen Ave &amp; W Chicago Ave</td>
<td style="text-align: right;">41.89581</td>
<td style="text-align: right;">-87.67852</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021-08-31 05:05:35</td>
<td style="text-align: left;">Homewood Ave &amp; 115th St</td>
<td style="text-align: right;">41.68460</td>
<td style="text-align: right;">-87.67071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-05-17 20:35:40</td>
<td style="text-align: left;">Bensley Ave &amp; 103rd St</td>
<td style="text-align: right;">41.70840</td>
<td style="text-align: right;">-87.56319</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021-08-31 05:05:35</td>
<td style="text-align: left;">Lincoln Ave &amp; Fullerton Ave</td>
<td style="text-align: right;">41.92591</td>
<td style="text-align: right;">-87.64926</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>A random sample of stations from the dataset is shown in <a href="#tbl-stations-in-use">Table&nbsp;8</a>. The timestamp indicates the first time a station appears as <em>In-Service</em> in the original dataset.</p>
<p>The active stations dataset is used to identify stations that were not listed as publicly available.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>unlisted_start <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    active_stations,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"start_station_name"</span> <span class="ot">=</span> <span class="st">"station_name"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">station_name =</span> start_station_name,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">station_id =</span> start_station_id</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>unlisted_end <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    active_stations,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"end_station_name"</span> <span class="ot">=</span> <span class="st">"station_name"</span>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">station_name =</span> end_station_name,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">station_id =</span> end_station_id</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>unlisted_stations <span class="ot">&lt;-</span> unlisted_start <span class="sc">%&gt;%</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(unlisted_end) <span class="sc">%&gt;%</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(station_name, station_id) <span class="sc">%&gt;%</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(station_name, station_id) <span class="sc">%&gt;%</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>unlisted_stations</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-unlisted-stations">
<table class="table table-sm table-striped">
<caption>Table&nbsp;9: Unlisted stations</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 46%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">station_name</th>
<th style="text-align: left;">station_id</th>
<th style="text-align: right;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Base - 2132 W Hubbard</td>
<td style="text-align: left;">Hubbard Bike-checking (LBS-WH-TEST)</td>
<td style="text-align: right;">1182</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base - 2132 W Hubbard Warehouse</td>
<td style="text-align: left;">Hubbard Bike-checking (LBS-WH-TEST)</td>
<td style="text-align: right;">963</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bissell St &amp; Armitage Ave - Charging</td>
<td style="text-align: left;">Bissell St &amp; Armitage Ave - Charging</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bissell St &amp; Armitage Ave - Charging</td>
<td style="text-align: left;">chargingstx1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DIVVY CASSETTE REPAIR MOBILE STATION</td>
<td style="text-align: left;">DIVVY CASSETTE REPAIR MOBILE STATION</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hastings WH 2</td>
<td style="text-align: left;">Hastings WH 2</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lincoln Ave &amp; Roscoe St - Charging</td>
<td style="text-align: left;">Lincoln Ave &amp; Roscoe St - Charging</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">NewHastings</td>
<td style="text-align: left;">2059 Hastings Warehouse Station</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pawel Bialowas - Test- PBSC charging station</td>
<td style="text-align: left;">Pawel Bialowas - Test- PBSC charging station</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Public Rack - Kedzie Ave &amp; 62nd Pl</td>
<td style="text-align: left;">1038</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Throop/Hastings Mobile Station</td>
<td style="text-align: left;">Throop/Hastings Mobile Station</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">WEST CHI-WATSON</td>
<td style="text-align: left;">DIVVY 001</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WEST CHI-WATSON</td>
<td style="text-align: left;">DIVVY 001 - Warehouse test station</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">WestChi</td>
<td style="text-align: left;">DIVVY 001 - Warehouse test station</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wilton Ave &amp; Diversey Pkwy - Charging</td>
<td style="text-align: left;">Wilton Ave &amp; Diversey Pkwy - Charging</td>
<td style="text-align: right;">38</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-unlisted-stations">Table&nbsp;9</a> summarises stations which appear in <code>bike_rides</code> without a corresponding match in the <code>active_stations</code> dataset.</p>
<p>The majority of stations in the table appear to have an operational function. Those ending with “- Charging” appear to be associated with testing of new charging stations prior to the company publicly announcing their availability.</p>
</section>
<section id="removing-identified-problems" class="level4">
<h4 data-anchor-id="removing-identified-problems">Removing identified problems</h4>
<p>Before proceeding with further manipulation and cleaning, the observations with identified problems should be removed. This is done using <code>dplyr::anti_join()</code> to filter the <code>bike_rides</code> dataset removing items matching those found in the <code>unlisted_stations</code> and <code>no_end_coords</code> data.frames.</p>
<div class="cell" data-hash="cyclistic_cache/html/tbl-remove-operational_b8432feec2c9b5fdde939e8f626eee88">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    unlisted_stations,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"start_station_name"</span> <span class="ot">=</span> <span class="st">"station_name"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    unlisted_stations,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"end_station_name"</span> <span class="ot">=</span> <span class="st">"station_name"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    no_end_coords,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"ride_id"</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">6</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-remove-operational">
<table class="table table-sm table-striped">
<caption>Table&nbsp;10: Sample of cleaned data</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ride_id</th>
<th style="text-align: left;">rideable_type</th>
<th style="text-align: left;">started_at</th>
<th style="text-align: left;">ended_at</th>
<th style="text-align: left;">start_station_name</th>
<th style="text-align: left;">start_station_id</th>
<th style="text-align: left;">end_station_name</th>
<th style="text-align: left;">end_station_id</th>
<th style="text-align: right;">start_lat</th>
<th style="text-align: right;">start_lng</th>
<th style="text-align: right;">end_lat</th>
<th style="text-align: right;">end_lng</th>
<th style="text-align: left;">member_casual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">4A633974C0BDB7AC</td>
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-08-11 17:09:12</td>
<td style="text-align: left;">2022-08-11 17:19:35</td>
<td style="text-align: left;">University Ave &amp; 57th St</td>
<td style="text-align: left;">KA1503000071</td>
<td style="text-align: left;">Kimbark Ave &amp; 53rd St</td>
<td style="text-align: left;">TA1309000037</td>
<td style="text-align: right;">41.79148</td>
<td style="text-align: right;">-87.59986</td>
<td style="text-align: right;">41.79957</td>
<td style="text-align: right;">-87.59475</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">29BB7E99AED8F3F0</td>
<td style="text-align: left;">electric_bike</td>
<td style="text-align: left;">2021-10-19 12:25:16</td>
<td style="text-align: left;">2021-10-19 12:29:53</td>
<td style="text-align: left;">900 W Harrison St</td>
<td style="text-align: left;">13028</td>
<td style="text-align: left;">Sangamon St &amp; Washington Blvd</td>
<td style="text-align: left;">13409</td>
<td style="text-align: right;">41.87479</td>
<td style="text-align: right;">-87.64978</td>
<td style="text-align: right;">41.88303</td>
<td style="text-align: right;">-87.65107</td>
<td style="text-align: left;">member</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7CC19BAD6C199498</td>
<td style="text-align: left;">electric_bike</td>
<td style="text-align: left;">2021-10-25 19:58:31</td>
<td style="text-align: left;">2021-10-25 20:08:18</td>
<td style="text-align: left;">Wilton Ave &amp; Diversey Pkwy</td>
<td style="text-align: left;">TA1306000014</td>
<td style="text-align: left;">Broadway &amp; Waveland Ave</td>
<td style="text-align: left;">13325</td>
<td style="text-align: right;">41.93244</td>
<td style="text-align: right;">-87.65281</td>
<td style="text-align: right;">41.94908</td>
<td style="text-align: right;">-87.64855</td>
<td style="text-align: left;">member</td>
</tr>
<tr class="even">
<td style="text-align: left;">A6E2C906370DDEA6</td>
<td style="text-align: left;">electric_bike</td>
<td style="text-align: left;">2022-07-20 15:20:28</td>
<td style="text-align: left;">2022-07-20 15:31:40</td>
<td style="text-align: left;">Clark St &amp; Elm St</td>
<td style="text-align: left;">TA1307000039</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">41.90262</td>
<td style="text-align: right;">-87.63180</td>
<td style="text-align: right;">41.89000</td>
<td style="text-align: right;">-87.65000</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1F32E534D31CC114</td>
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-08-01 13:12:18</td>
<td style="text-align: left;">2022-08-01 13:29:00</td>
<td style="text-align: left;">Laramie Ave &amp; Gladys Ave</td>
<td style="text-align: left;">543</td>
<td style="text-align: left;">Cicero Ave &amp; Flournoy St</td>
<td style="text-align: left;">16912</td>
<td style="text-align: right;">41.87581</td>
<td style="text-align: right;">-87.75529</td>
<td style="text-align: right;">41.87213</td>
<td style="text-align: right;">-87.74662</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">08BD94378025058A</td>
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-08-03 17:58:12</td>
<td style="text-align: left;">2022-08-03 18:11:51</td>
<td style="text-align: left;">Clark St &amp; Ida B Wells Dr</td>
<td style="text-align: left;">TA1305000009</td>
<td style="text-align: left;">Sangamon St &amp; Lake St</td>
<td style="text-align: left;">TA1306000015</td>
<td style="text-align: right;">41.87593</td>
<td style="text-align: right;">-87.63058</td>
<td style="text-align: right;">41.88578</td>
<td style="text-align: right;">-87.65102</td>
<td style="text-align: left;">member</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-remove-operational">Table&nbsp;10</a> shows a sample of the dataset after initial cleaning.</p>
</section>
<section id="ride-duration" class="level4">
<h4 data-anchor-id="ride-duration">Ride duration</h4>
<section id="adding-ride-duration-time-and-day-of-week" class="level5">
<h5 data-anchor-id="adding-ride-duration-time-and-day-of-week">Adding Ride Duration, Time and Day of Week</h5>
<p>To add analysis calculated columns for the length of ride, the hour the ride started and the day of week are added to the dataset.</p>
<div class="cell" data-hash="cyclistic_cache/html/tbl-add-duration_be75b1b0246111fe383f45d0a9a22530">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_int =</span> started_at <span class="sc">%--%</span> ended_at,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ride_time =</span> <span class="fu">as.duration</span>(ride_int),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour =</span> <span class="fu">hour</span>(started_at),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">day =</span> <span class="fu">wday</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.before =</span> start_station_name</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ride_id, <span class="sc">-</span>ride_int) <span class="sc">%&gt;%</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">6</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-add-duration">
<table class="table table-sm table-striped">
<caption>Table&nbsp;11: Sample of rides with duration</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">rideable_type</th>
<th style="text-align: left;">started_at</th>
<th style="text-align: left;">ended_at</th>
<th style="text-align: right;">ride_time</th>
<th style="text-align: right;">hour</th>
<th style="text-align: left;">day</th>
<th style="text-align: left;">start_station_name</th>
<th style="text-align: left;">start_station_id</th>
<th style="text-align: left;">end_station_name</th>
<th style="text-align: left;">end_station_id</th>
<th style="text-align: right;">start_lat</th>
<th style="text-align: right;">start_lng</th>
<th style="text-align: right;">end_lat</th>
<th style="text-align: right;">end_lng</th>
<th style="text-align: left;">member_casual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-08-31 14:51:47</td>
<td style="text-align: left;">2022-08-31 15:09:00</td>
<td style="text-align: right;">1033s (~17.22 minutes)</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Wed</td>
<td style="text-align: left;">Clark St &amp; Winnemac Ave</td>
<td style="text-align: left;">TA1309000035</td>
<td style="text-align: left;">Montrose Harbor</td>
<td style="text-align: left;">TA1308000012</td>
<td style="text-align: right;">41.97335</td>
<td style="text-align: right;">-87.66786</td>
<td style="text-align: right;">41.96398</td>
<td style="text-align: right;">-87.63818</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2021-09-15 16:37:58</td>
<td style="text-align: left;">2021-09-15 16:48:35</td>
<td style="text-align: right;">637s (~10.62 minutes)</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Wed</td>
<td style="text-align: left;">Clark St &amp; Elm St</td>
<td style="text-align: left;">TA1307000039</td>
<td style="text-align: left;">Clinton St &amp; Washington Blvd</td>
<td style="text-align: left;">WL-012</td>
<td style="text-align: right;">41.90297</td>
<td style="text-align: right;">-87.63128</td>
<td style="text-align: right;">41.88338</td>
<td style="text-align: right;">-87.64117</td>
<td style="text-align: left;">member</td>
</tr>
<tr class="odd">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-04-10 18:09:29</td>
<td style="text-align: left;">2022-04-10 18:15:02</td>
<td style="text-align: right;">333s (~5.55 minutes)</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Sun</td>
<td style="text-align: left;">DuSable Lake Shore Dr &amp; Monroe St</td>
<td style="text-align: left;">13300</td>
<td style="text-align: left;">Field Blvd &amp; South Water St</td>
<td style="text-align: left;">15534</td>
<td style="text-align: right;">41.88096</td>
<td style="text-align: right;">-87.61674</td>
<td style="text-align: right;">41.88635</td>
<td style="text-align: right;">-87.61752</td>
<td style="text-align: left;">member</td>
</tr>
<tr class="even">
<td style="text-align: left;">classic_bike</td>
<td style="text-align: left;">2022-07-02 14:26:46</td>
<td style="text-align: left;">2022-07-02 14:29:40</td>
<td style="text-align: right;">174s (~2.9 minutes)</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Sat</td>
<td style="text-align: left;">DuSable Lake Shore Dr &amp; North Blvd</td>
<td style="text-align: left;">LF-005</td>
<td style="text-align: left;">Clark St &amp; North Ave</td>
<td style="text-align: left;">13128</td>
<td style="text-align: right;">41.91172</td>
<td style="text-align: right;">-87.62680</td>
<td style="text-align: right;">41.91197</td>
<td style="text-align: right;">-87.63194</td>
<td style="text-align: left;">member</td>
</tr>
<tr class="odd">
<td style="text-align: left;">docked_bike</td>
<td style="text-align: left;">2021-09-03 14:51:56</td>
<td style="text-align: left;">2021-09-03 15:22:12</td>
<td style="text-align: right;">1816s (~30.27 minutes)</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Fri</td>
<td style="text-align: left;">Streeter Dr &amp; Grand Ave</td>
<td style="text-align: left;">13022</td>
<td style="text-align: left;">Sheffield Ave &amp; Wrightwood Ave</td>
<td style="text-align: left;">TA1309000023</td>
<td style="text-align: right;">41.89228</td>
<td style="text-align: right;">-87.61204</td>
<td style="text-align: right;">41.92871</td>
<td style="text-align: right;">-87.65383</td>
<td style="text-align: left;">casual</td>
</tr>
<tr class="even">
<td style="text-align: left;">electric_bike</td>
<td style="text-align: left;">2022-07-20 12:20:32</td>
<td style="text-align: left;">2022-07-20 12:42:28</td>
<td style="text-align: right;">1316s (~21.93 minutes)</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">Wed</td>
<td style="text-align: left;">Theater on the Lake</td>
<td style="text-align: left;">TA1308000001</td>
<td style="text-align: left;">Lakefront Trail &amp; Bryn Mawr Ave</td>
<td style="text-align: left;">15576</td>
<td style="text-align: right;">41.92625</td>
<td style="text-align: right;">-87.63100</td>
<td style="text-align: right;">41.98404</td>
<td style="text-align: right;">-87.65228</td>
<td style="text-align: left;">member</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-add-duration">Table&nbsp;11</a> shows a sample of the resulting dataset with added columns.</p>
<p>Minimum and maximum ride times can now be checked for plausibility.</p>
<div class="cell" data-hash="cyclistic_cache/html/tbl-ride-min-max_5341c66ca45b33958ccb0c1054d335da">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Minimum =</span> <span class="fu">min</span>(ride_time) <span class="sc">/</span> <span class="dv">3600</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Maximum =</span> <span class="fu">max</span>(ride_time) <span class="sc">/</span> <span class="dv">3600</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-ride-min-max">
<table class="table table-sm table-striped">
<caption>Table&nbsp;12: Summary of ride duration (hours)</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-2.290278</td>
<td style="text-align: right;">678.4169</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Rides with negative duration should not occur, so this needs to be checked and corrected.</p>
</section>
<section id="addressing-negative-ride-durations" class="level5">
<h5 data-anchor-id="addressing-negative-ride-durations">Addressing negative ride durations</h5>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">floor_date</span>(<span class="fu">as.Date</span>(started_at), <span class="st">"month"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">nrt =</span> <span class="fu">mean</span>(ride_time <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(month, nrt)) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Rides with negative duration"</span>,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Month"</span>,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage of Rides"</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<p><img src="cyclistic_files/figure-html/unnamed-chunk-22-1.svg" width="672"></p>
</div>
</div>
<p>The plot indicates that the precentage rides with negative ride durations is around three times higher in November than the next highest month - September.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">month</span>(started_at) <span class="sc">==</span> <span class="dv">11</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">"Day"</span> <span class="ot">=</span> <span class="fu">day</span>(started_at)) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">"Percent Negative"</span> <span class="ot">=</span> <span class="fu">mean</span>(ride_time <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Percent Negative</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-days-neg-rides">
<table class="table table-sm table-striped">
<caption>Table&nbsp;13: Days in November 2021 with negative ride time</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Day</th>
<th style="text-align: right;">Percent Negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.2781276</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>All rides with negative duration in November occurred on the 7th.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">month</span>(started_at) <span class="sc">==</span> <span class="dv">11</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">day</span>(started_at) <span class="sc">==</span> <span class="dv">7</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">Hour =</span> <span class="fu">hour</span>(started_at)) <span class="sc">%&gt;%</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Percent Negative"</span> <span class="ot">=</span> <span class="fu">mean</span>(ride_time <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Count =</span> <span class="fu">sum</span>(ride_time <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Percent Negative</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<div id="tbl-hour-neg-rides">
<table class="table table-sm table-striped">
<caption>Table&nbsp;14: Negative ride duration by hour</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Hour</th>
<th style="text-align: right;">Percent Negative</th>
<th style="text-align: right;">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.51587</td>
<td style="text-align: right;">53</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><a href="#tbl-hour-neg-rides">Table&nbsp;14</a> shows that all negative ride durations on 7th November were taken between 1.00am and 2.00am. This coincides with the end of daylight savings in Chicago. At 2.00am clocks went back one hour to 1.00am.</p>
<p>Ride start and end timestamp values in the dataset do not include timezone information. Timestamps between 1.00am and 2.00am could refer to either Central Daylight Time or Central Standard Time meaning there is an ambiguity which is very difficult to resolve.</p>
<p>The negative duration of rides which start and end between 1.00am and 2.00am can be resolved by adding 60 minutes. However the ambiguity of the rides which have one end point in this time range remains.</p>
<p>I recommend that timezone be recorded as part of the timestamp in future to avoid these issues.</p>
<p>For the present analysis I’ve chosen to correct the negative timestamps between 1.00am and 2.00am and to leave the ambiguous timestamps unaltered.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_time =</span> <span class="fu">if_else</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    (ride_time <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">&amp;</span> (<span class="fu">date</span>(started_at) <span class="sc">==</span> <span class="fu">date</span>(<span class="st">"2021-11-07"</span>)),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    ride_time <span class="sc">+</span> <span class="dv">3600</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    ride_time</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  ))</span></code></pre></div>
</details>
</div>
</section>
<section id="other-ride-duration-issues" class="level5">
<h5 data-anchor-id="other-ride-duration-issues">Other ride duration issues</h5>
<p>The Cyclistic website indicates that rides of less than 60 seconds have been removed from the dataset. Cyclistic also state that if rides exceed 24 hours the bike is treated as stolen and the user is fined $1200.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="ot">&lt;-</span> bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_time <span class="sc">&gt;=</span> <span class="dv">60</span>, ride_time <span class="sc">&lt;=</span> <span class="dv">21600</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual, rideable_type) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">as.numeric</span>(<span class="fu">median</span>(ride_time), <span class="at">units =</span> <span class="st">"secs"</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(ride_time))),</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">exp</span>(<span class="fu">sd</span>(<span class="fu">log</span>(ride_time))),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">iqr =</span> <span class="fu">IQR</span>(ride_time),</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">outliers =</span> <span class="fu">quantile</span>(ride_time, <span class="fl">0.75</span>) <span class="sc">+</span> iqr <span class="sc">*</span> <span class="fl">1.5</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'member_casual'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">member_casual</th>
<th style="text-align: left;">rideable_type</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">iqr</th>
<th style="text-align: right;">outliers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">member</td>
<td style="text-align: left;">classic_bike</td>
<td style="text-align: right;">576</td>
<td style="text-align: right;">580.8936</td>
<td style="text-align: right;">2.164365</td>
<td style="text-align: right;">656</td>
<td style="text-align: right;">1978s (~32.97 minutes)</td>
</tr>
<tr class="even">
<td style="text-align: left;">member</td>
<td style="text-align: left;">electric_bike</td>
<td style="text-align: right;">517</td>
<td style="text-align: right;">523.0511</td>
<td style="text-align: right;">2.171498</td>
<td style="text-align: right;">579</td>
<td style="text-align: right;">1753.5s (~29.23 minutes)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">classic_bike</td>
<td style="text-align: right;">907</td>
<td style="text-align: right;">952.9159</td>
<td style="text-align: right;">2.380691</td>
<td style="text-align: right;">1101</td>
<td style="text-align: right;">3287.5s (~54.79 minutes)</td>
</tr>
<tr class="even">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">docked_bike</td>
<td style="text-align: right;">1664</td>
<td style="text-align: right;">1733.8565</td>
<td style="text-align: right;">2.455082</td>
<td style="text-align: right;">2152</td>
<td style="text-align: right;">6350s (~1.76 hours)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">electric_bike</td>
<td style="text-align: right;">722</td>
<td style="text-align: right;">742.7065</td>
<td style="text-align: right;">2.280275</td>
<td style="text-align: right;">836</td>
<td style="text-align: right;">2517s (~41.95 minutes)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>n3 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">nrow</span>(bike_rides) <span class="sc">*</span> <span class="fl">0.001</span>, <span class="dv">0</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>bike_rides <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(ride_time, <span class="at">n =</span> n3) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min =</span> <span class="fu">min</span>(ride_time) <span class="sc">/</span> <span class="dv">3600</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max =</span> <span class="fu">max</span>(ride_time) <span class="sc">/</span> <span class="dv">3600</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5759</td>
<td style="text-align: right;">3.546111</td>
<td style="text-align: right;">5.999444</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
</div> <!-- /content -->



</body></html>